### ISSUE TITLE
️🛠 - Sending from L2 -> L1 with ledger shows incorrect amount

### ISSUE THREAD

**Issue by Tuditi** [bloomwalletio/bloom#571]
### Task description

Sometimes it happens that L2 -> L1 shows an incorrect amount, which means that one of the props is not passed down properly.

![image](https://github.com/bloomwalletio/bloom/assets/45079109/64cb485a-943a-4130-b7ec-7bd859dbbb6f)

![image](https://github.com/bloomwalletio/bloom/assets/45079109/633e6bda-40f0-483c-9e00-aeeddb2de6bc)

### Requirements

- [ ] Correct amount shows in Ledger device
- [ ] Correct amount shows in verification pop-up

**Comment by maxwellmattryan** [comment]
I am not sure if we can fix this because the reason why `0` is showed in the UI is b/c that's what the device shows, and I feel it's important to match that above all else. 

But perhaps we could show a hint to the user somewhere saying that this is expected and that the "transfer" is actually within the data of the transaction?

**Comment by maxwellmattryan** [comment]
I think this issue can be more focused around the UX wrt Ledger devices. I created a task for the activity part of it (#614).

**Comment by MarkNerdi** [comment]
This issue is related to the way we generate the `Send` activity. Currently we only generate correct activities for the base token, because thats a `value` transfer. 
Unwrapping and native tokens are data transfers, and to display those correctly, we need to be able to parse the data and interpret this

**Comment by MarkNerdi** [comment]
Tracked in https://github.com/bloomwalletio/bloom/issues/653
